# Useful links
github_username: "Nervi0zz0"
#facebook_username: "<facebook_username>"
#twitter_username: "<twitter_username>"
linkedin_id: "jmam84"

# Theme
# theme: jekyll-theme-potato-hacker                 # Uncomment this
# remote_theme: luxedo/jekyll-theme-potato-hacker   # Or this
theme_repository: "https://github.com/luxedo/jekyll-theme-potato-hacker"
theme_base: "dark"       # Theme palette (light | dark)
theme_switch: on         # Show color switch (on | off)

# Extra settings
blog: on                 # Show blog tag and post list (on | off)
avatar: on               # Show avatar (on | off)
recent_posts: 3          # Number of recent posts to display
avatar_image: "assets/img/jimy.jpeg"
avatar_description: "Bienvenido al 'Diario de un Cojo'."
highlighter_theme: monokai  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - dropdown2
  - About
  - dropdown1

# Collections
collections:
  dropdown:
    output: true
  items:
    output: true

   dropdown1:  # Plataformas de estudio, ordenadas alfabéticamente
    - BlueTeamsLabs
    - LetsDefend
    - TryHackMe
  dropdown2:  # Notas Secretas del SOC
    - Notas Secretas del SOC
  
